// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DotTest.Models
{
    public partial class Order
    {
        public int OrderId { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public int CustomerId { get; set; }

        public virtual Customer Customer { get; set; }
    }
}